:%s/\s\+$/
:g/[a-z]= /d
:%s/'/''/g
:%s/^  action: .*/&': [/
:%s/^  action: /  \\\ '/
:g/^- name:/d
:%s/#\_.\{-}\(^  \\ \')\@=/', 'menu': '\0'},/
:%s/^\s\+\(\w\+\)/      \\\  {'word': '\1=/
:%s/^$/  \\\ ],/
ggOlet optargs = {
ggO" Auto-generated by txt2optargs.vim
Go  \ }
:w! gen/optargs.vim
:q!
